[package]
name = "tower-sessions-surrealdb-store"
version = "0.1.0"
edition = "2021"
description = "SurrealDB session store. Not for direct use; see the `tower-sessions` crate for details."
authors = ["Calum Sieppert <sieppertcalum@gmail.com>"]
license = "MIT"
homepage = "https://github.com/rynoV/tower-sessions-surrealdb-store"
keywords = ["axum", "session", "sessions", "cookie", "tower", "surrealdb"]
categories = ["asynchronous", "network-programming", "web-programming"]
repository = "https://github.com/rynoV/tower-sessions-surrealdb-store"
documentation = "https://docs.rs/tower-sessions-surrealdb-store"
readme = "README.md"
resolver = "2"

[dependencies]
async-trait = "0.1.75"
rmp-serde = "1.1.2"
serde = "1.0.193"
surrealdb = { version = "1.0.2", optional = true }
surrealdb-nightly = { version = "1.20231219.1034735", optional = true }
thiserror = "1.0.51"
# Fix once resolved with tower-sessions maintainers
tower-sessions-core = { path = "../tower-sessions/tower-sessions-core" }
tracing = "0.1.40"

[features]
default = ["surrealdb"]
surrealdb = ["dep:surrealdb"]
surrealdb-nightly = ["dep:surrealdb-nightly"]

[dev-dependencies]
axum = "0.7.2"
axum-core = "0.4.1"
serde_json = "1.0.108"
surrealdb = { version = "1.0.2", features = ["kv-mem"] }
tokio = "1.35.1"
tokio-test = "0.4.3"
tower = "0.4.13"
# Fix once resolved with tower-sessions maintainers
tower-sessions = { path = "../tower-sessions/", features = ["deletion-task"] }

[[example]]
name = "counter"
